project:
  type: book
  output-dir: docs

book:
  title: "Webscraping Tutorial"
  author: "Jonathan Jayes"
  favicon: assets/favicon.ico
  date: "8/25/2024"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-virtual-envs.qmd
    - 03-scraping-basics.qmd
    - 04-scraping-sars.qmd
    - 05-github-actions.qmd
    - 06-streamlit-app.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
    - cosmo
    - assets/custom.scss
    css: assets/styles.css
  pdf:
    documentclass: scrreprt