## Preface {.unnumbered}

Welcome to this tutorial on web scraping using Python, Lisa, Jacques and Almaro! Whether you're new to programming or looking to enhance your skills in data extraction, this course is designed to guide you through the essential techniques of web scraping. Throughout the tutorial, we will cover everything from setting up your Python environment to scraping simple websites, extracting structured data from tables, automating your scraping tasks, and even building an interactive web application.

One of the additional benefits of this course is the opportunity to deepen your understanding of Python itself. Python is a versatile scripting language that’s not only powerful but also widely supported. This means that there's a wealth of information available online, and chatbots like ChatGPT are particularly skilled at generating Python code that works effectively.

To enhance your learning experience, I’ve included videos from Vincent at Calmcode for almost every chapter. Vincent’s tutorials are high-quality, well-explained, and can provide you with deeper insights into both Python and web scraping. If you find yourself needing more information or a different perspective on a topic, I highly recommend checking out his Calmcode courses.

To get started with Python, here's a brief introductory video that explains the basics:

<iframe width="560" height="315" src="https://www.youtube.com/embed/x7X9w_GIm1s?si=YeaSleUxKTaom9w6&amp;controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

In addition to the Calmcode videos and other resources, remember that the Python community is vast and supportive. Whether you’re troubleshooting an issue or looking for guidance on a specific task, there’s a good chance you’ll find help online.

I hope you find this course both informative and enjoyable. Let’s get started with web scraping, and don’t forget to explore the Calmcode videos included in each chapter to further enhance your learning experience. Happy coding!